sudo: required

services:
  - docker

before_script:
  - cp Configuration.mk.example Configuration.mk
  - docker build --tag esper-build .

script:
  - docker run -it --rm --volume $(pwd):/home/builder/site --volume $(pwd):/home/builder/esper esper-build
